
const defaultStore = {
  course_d: [[[{
    place: '东3211',
    course: '计算机操作系统',
    teacher: '马立平',
    week: [1,2,3,4,5,6],
    start_section: 1,
    section_length: 2
  }, {
    place: '东3211',
    course: '计算机网络',
    teacher: '马立平',
    week: [6,7,8,9,10],
    start_section: 1,
    section_length: 2
  }], [{
    place: '东3211',
    course: '数据库',
    teacher: '马立平',
    week: [2,3,4,5,6,8,9],
    start_section: 2,
    section_length: 2
  }]], [[{
    place: '东3211',
    course: '计算机操作系统',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 2
  }, {
    place: '东3211',
    course: '计算机网络',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 4
  }], [{
    place: '东3211',
    course: '数据库',
    teacher: '马立平',
    week: [2,3,4,5,6,8,9],
    start_section: 3,
    section_length: 2
  }]], [[{
    place: '东3211',
    course: '计算机操作系统',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 2
  }, {
    place: '东3211',
    course: '计算机网络',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 4
  }], [{
    place: '东3211',
    course: '数据库',
    teacher: '马立平',
    week: [2,3,4,5,6,8,9],
    start_section: 3,
    section_length: 2
  }]], [[{
    place: '东3211',
    course: '计算机操作系统',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 2
  }, {
    place: '东3211',
    course: '计算机网络',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 4
  }], [{
    place: '东3211',
    course: '数据库',
    teacher: '马立平',
    week: [2,3,4,5,6,8,9],
    start_section: 3,
    section_length: 2
  }]], [[{
    place: '东3211',
    course: '计算机操作系统',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 2
  }, {
    place: '东3211',
    course: '计算机网络',
    teacher: '马立平',
    week: [1,3,4,5,6,7,8,9,10],
    start_section: 1,
    section_length: 4
  }], [{
    place: '东3211',
    course: '数据库',
    teacher: '马立平',
    week: [2,3,4,5,6,8,9],
    start_section: 5,
    section_length: 4
  }]], [], []],
  
}

const course = (state = defaultStore) => {
  return state
}

export default course
